# Generated by Django 4.2.1 on 2023-05-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassName', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='class_image',
            field=models.ImageField(null=True, upload_to='uploads/subject_images/'),
        ),
    ]
